#!/bin/bash
echo "Enter user to delete:"
read username
real_user='cat /etc/passwd |grep $username'
if ["$real_user" != "$NULL"]
then
	sudo passwd -l $username 
	if [ "$(pgrep -u $username)" != "$NULL" ]
	then
		sudo kill -15 $(pgrep -u $username)
fi
userdel -r $username

